language: node_js
node_js:
addons:
  firefox: "50.1.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm run install-geckodriver
  - npm prune
script:
  - npm run commit
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
